services:
  frontend:
    build: .
    container_name: agrimarket-frontend
    ports:
      - "3067:3000"
    environment:
      - NODE_ENV=production
      - BACKEND_URL=${BACKEND_URL}
    dns:
      - 8.8.8.8
      - 1.1.1.1
    restart: unless-stopped